name: "Book GitHub Pages"

on:
  push:
    branches: [$default-branch]

  # Allows running this workflow manually
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: actions/configure-pages@v3
      - name: "Build documentation book"
        run: |
          nix build '.#book' --print-build-logs
          cp -Lr ./result/ ./book
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./book
      - uses: actions/deploy-pages@v2
