name: "Build"

permissions: read-all

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@V27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: "Build"
      run: nix flake check
