name: "Check EditorConfig"

permissions: read-all

on:
  push:
  pull_request:

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@V28
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: "Check EditorConfig"
      run: nix run 'nixpkgs#eclint' --inputs-from .
