name: "Check Formatting"

permissions: read-all

on:
  push:
  pull_request:

jobs:
  alejandra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@V28
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: "Check Formatting"
      run: nix fmt -- --check .
